server:
  port: 8090

spring:
  application:
    name: authentication

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3307/mydb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/