services:
  db:
    image: mysql:latest
    container_name: my_rdb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: TOROMBOLINE_BOOK_STORE
      MYSQL_USER: user_1
      MySQL_PASSWORD: user_1234
    ports:
      - 3307:3306
    volumes:
      - my-db-volume:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  my-db-volume:
