server:
  port: 8091

spring:
  application:
    name: t-book-gateway

  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: YOUR_SECRET_KEY_HERE # If using symmetric key (HS256)
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/